services:
  db:
    image: mariadb:11.4
    container_name: dadamda-db
    restart: unless-stopped

    environment:
      MARIADB_DATABASE: dadamda
      MARIADB_USER: dadamda
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: root
      TZ: Asia/Seoul

    ports:
      - "3307:3306"

    volumes:
      - ./mariadb/data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - dadamda-network

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: dadamda-server
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/dadamda?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: dadamda
      SPRING_DATASOURCE_PASSWORD: 1234

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect

      TZ: Asia/Seoul

    networks:
      - dadamda-network


networks:
  dadamda-network:
    driver: bridge